"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f5141dc12ef'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('is_orphan', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_files_scan_id'), 'code_files', ['scan_id'], unique=False)
    op.create_table('contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('last_commit_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributors_email'), 'contributors', ['email'], unique=False)
    op.create_index(op.f('ix_contributors_scan_id'), 'contributors', ['scan_id'], unique=False)
    op.create_table('authored_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('lines_owned', sa.Integer(), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['code_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authored_edges_contributor_id'), 'authored_edges', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_authored_edges_file_id'), 'authored_edges', ['file_id'], unique=False)
    op.create_index(op.f('ix_authored_edges_scan_id'), 'authored_edges', ['scan_id'], unique=False)
    op.add_column('findings', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'metadata')
    op.drop_index(op.f('ix_authored_edges_scan_id'), table_name='authored_edges')
    op.drop_index(op.f('ix_authored_edges_file_id'), table_name='authored_edges')
    op.drop_index(op.f('ix_authored_edges_contributor_id'), table_name='authored_edges')
    op.drop_table('authored_edges')
    op.drop_index(op.f('ix_contributors_scan_id'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_email'), table_name='contributors')
    op.drop_table('contributors')
    op.drop_index(op.f('ix_code_files_scan_id'), table_name='code_files')
    op.drop_table('code_files')
    # ### end Alembic commands ###
