"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56120b5d9a9'
down_revision: Union[str, None] = '4f5141dc12ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_key', sa.String(length=255), nullable=False),
    sa.Column('rule_text', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_rules_repo_key'), 'candidate_rules', ['repo_key'], unique=False)
    op.create_table('github_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_installations_installation_id'), 'github_installations', ['installation_id'], unique=True)
    op.create_table('pr_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_key', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_cache_repo_key'), 'pr_cache', ['repo_key'], unique=False)
    op.create_table('github_installation_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('repo_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['github_installations.installation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_installation_repos_installation_id'), 'github_installation_repos', ['installation_id'], unique=False)
    op.create_index(op.f('ix_github_installation_repos_repo_key'), 'github_installation_repos', ['repo_key'], unique=True)
    op.create_table('pr_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pr_cache.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_comments_pr_id'), 'pr_comments', ['pr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pr_comments_pr_id'), table_name='pr_comments')
    op.drop_table('pr_comments')
    op.drop_index(op.f('ix_github_installation_repos_repo_key'), table_name='github_installation_repos')
    op.drop_index(op.f('ix_github_installation_repos_installation_id'), table_name='github_installation_repos')
    op.drop_table('github_installation_repos')
    op.drop_index(op.f('ix_pr_cache_repo_key'), table_name='pr_cache')
    op.drop_table('pr_cache')
    op.drop_index(op.f('ix_github_installations_installation_id'), table_name='github_installations')
    op.drop_table('github_installations')
    op.drop_index(op.f('ix_candidate_rules_repo_key'), table_name='candidate_rules')
    op.drop_table('candidate_rules')
    # ### end Alembic commands ###
